module Server where

import Signal as S
import Http

serverUrl = "http://192.168.1.212:8000/"

fileName : Signal String
fileName = S.constant "main_street.txt"

textContent : Signal String
textContent = let req = S.map (\x -> Http.get (serverUrl ++ "texts/"  ++ x)) fileName
                  response = Http.send <| req
                  getContent : Http.Response String -> String
                  getContent response = case response of
                      Http.Success str -> defaultText
                      Http.Waiting     -> defaultText
                      Http.Failure _ _ -> defaultText
              in S.map getContent response

defaultText ="""
Inventions

ISAAC BASHEVIS SINGER

Since moving to the country, I find myself growing sleepy by ten o’clock at night. I retire at the same time as my parakeets and the chickens in the coop. In bed, I peruse “Phantasms of the Living,” but I must soon turn off the light. A dreamless sleep—or one with dreams I can’t recall—takes hold of me until two in the morning. At two, I wake up completely rested, my head buzzing with plans and possibilities. On the winter night I will describe, it came to me to write about a Communist—in fact, a Communist theoretician—who attends a leftist conference on world peace and sees a ghost. I saw it all clearly: the meeting hall, the portraits of Marx and Engels, the table covered with a green cloth, the Communist, Morris Krakower, a short, stocky man with a head of close-cropped hair and a pair of steely eyes behind thick-lensed pince-nez. The conference takes place in Warsaw in the thirties, the era of Stalinist terror and the Moscow Trials. Morris Krakower disguises his defense of Stalin in the jargon of Marxist theory, but everyone grasps his meaning. In his speech, he proclaims that only the dictatorship of the proletariat can insure peace, and, therefore, no deviation either to the right or to the left can be tolerated. World peace is in the hands of the N.K.V.D.

After the reports, the delegates congregate for a friendly glass of tea. Again, Comrade Krakower holds forth. Officially, he is one of the delegates, but in reality he is a representative of the Comintern. His goatee is reminiscent of Lenin’s; his voice has a hard metallic ring. He is thoroughly grounded in Marxism and knows several languages; he has delivered lectures at the Sorbonne. Twice a year, he travels to Moscow. And, as if all this were not sufficient, he is also the son of a rich man: his father owns oil wells near Drohobycz. He doesn’t have to be a paid Party functionary.

Morris Krakower is clever at conspiracy, but intrigue isn’t necessary here. The press is admitted to the sessions; the police have infiltrated their spies, but Morris needn’t fear arrest. Even if he were arrested, it would be no great tragedy. In prison, he could devote his time to reading. He would smuggle out manuscripts to arouse the masses. A few weeks of prison can only enhance the prestige of a Party worker.

Outdoors, there’s a frost. Toward evening, snow falls. The tea drinking ends, and Morris Krakower heads for his hotel. The streets are smooth, white fields through which trolley cars glide half-empty. The shopkeepers have all lowered their window shades and are fast asleep. Above the rooftops, numberless stars glitter. If intelligent beings exist on other planets, Krakower reflects, perhaps their lives are also regulated by five-year plans. He smiles at the thought. His thick lips part, revealing large, square teeth.

A madwoman sits on the curb. Next to her is a basket full of old newspapers and rags. Withdrawn and dishevelled, her eyes shining fiercely, she converses with her demon. Somewhere nearby, a tomcat yowls. A night watchman in a fur jacket and hood is checking the shopkeepers’ locks. Morris Krakower goes into his hotel, gets the key from the clerk, and takes the elevator to the fourth floor. The long corridor reminds him of a prison. He opens the door to his room and enters. The chambermaid has changed the bed linen. All he needs to do is undress. Tomorrow, the conference starts late, so Morris will be able to catch up on sleep.

He puts on new pajamas. How uncharismatic a barefoot leader in ill-fitting pajamas looks! He lies down on the bed and turns out the light on the night table. The room is dark and cool, and he falls asleep immediately.

Suddenly, he feels the blanket being pulled at his feet. He wakes up. What can it be? Is there a cat in the room? A dog? He shakes off his sleepiness and turns on the light. No, there’s no one there. He must have imagined it. He turns the light out and goes to sleep, but someone starts to pull the blanket again. Morris has to pull it back or else become uncovered. “What kind of business is this?” he asks himself. He turns on the light once more. Apparently, his nerves are on edge. He is surprised, because he is in good health and well rested lately. Everything is going smoothly at the conference.

He removes the blanket and examines the sheets. He gets out of bed and checks to make sure the door is chained. He peeks into the closet. Nothing. “Well, I must have been dreaming,” he concludes, although he knows it was no dream. “A hallucination?” Morris Krakower is annoyed at himself. He turns out the light and goes back to bed. “Enough of this stupidity!”

But someone is definitely pulling the blanket again. Morris sits up in bed with such force that the mattress springs ring out. Someone, some invisible being, is pulling the blanket and pulling it with the strength of human hands. Morris doesn’t move a muscle. Have I gone out of my mind? he thinks. Am I suffering from a nervous breakdown?

He releases the blanket, and the invisible presence, the power whose existence is impossible, immediately draws it toward the foot of the bed. Morris is uncovered to the knees. “What the devil is this?” he says aloud. He doesn’t want to admit it, but he is frightened. He can hear his heart pounding. There must be some explanation. It can’t be a ghost.

As soon as the word enters his mind, terror grips him. Maybe this is some kind of sabotage. But by whom? And how? The blanket has fallen off the bed entirely. Morris wants to turn the light on, but he can’t find the switch. His feet are cold, but his head is hot. By accident he knocks the lamp off the night table. He jumps out of bed and tries to turn on the overhead light, but he bumps into a chair. He reaches the switch and turns on the light. The blanket is lying on the floor. The parchment lampshade has toppled from the lamp. Again, Morris looks in the closet, goes to the window and raises the blinds. The street is white, empty. He searches for a door leading to another room, but there isn’t one. He bends down and feels around under the bed, opens the door to the corridor. No one is there. “Should I call the porter? But what can I tell him? No, I can’t make a fool of myself!” he decides. He closes the door, locks it, and lets the blinds down. He replaces the blanket on the bed and sets the lampshade back on the lamp. “This is insane,” he mutters.

Morris Krakower has broken out in a sweat, though the room is cold. The palms of his hands are moist. “It must be some kind of neurasthenia,” he says, trying to reassure himself. He considers leaving the light on for a while, but is ashamed at his cowardice. “I must not allow myself to fall victim to such superstition!” He switches the light off and walks unsteadily back to his bed. He is no longer the same self-confident Morris Krakower, spokesman for the Comintern. He is a frightened man. Will whatever it is start pulling the blanket again?

For a while, Morris lies motionless. The blanket doesn’t budge. Outside the window, he hears the muffled clanging of a trolley car. He is still in the center of a civilized city and not in a desert or at the North Pole. “It’s all in my mind!” he reasons. “I must sleep!” He shuts his eyes. Immediately he senses a tug. No, it isn’t just a tug but a strong yank. In a second, it has dragged the blanket down to his hips. Morris reaches out, grabs the blanket, and tries to jerk it back quickly. But he has to exert all his strength, because his nocturnal visitor is pulling powerfully in the opposite direction. The visitor is stronger, and Morris must yield. He wheezes, grunts, reviles him. The brief struggle leaves Morris covered with perspiration. “What woes have befallen me!” he says, repeating an expression his mother used. That such utter madness should happen to him, of all people! What could it be? “God in Heaven, can there really be demons? If so, then everything falls apart.”

I had fallen asleep and dreamed one of those dreams which recur again and again over the years. I am in a windowless cellar. I either live there or use it as a hideout. The cellar is deep, dark, the dirt floor rutted and mounded. I am afraid, but I know that I must remain there for some time. I open a door and find myself in another small dark room with a straw bed that has no bedding. I sit down on the bed and try to talk myself out of my fear, but it only grows. I hear noises. Dark creatures, soft as cobwebs, creep about in the corridor, whispering. I must escape, but the way back is blocked. I go toward a second exit, but is it there? The corridor narrows, twists, descends. I am no longer walking but crawling, wormlike, toward an opening, but will I reach it? Wait! I’ve left something in the other room—a document, a manuscript—and I must go back for it. This isn’t the only complication. It’s extraordinary, but growths resembling antlers have sprouted on my arms. The last few seconds of the dream are thick with tortuous difficulties too bizarre and numerous to remember. The whole thing is fast becoming ludicrous, and even in my sleep I know that I must awaken from this nightmare, because the power that guides dreams never wishes to risk revealing itself. It is poking fun at its own devices. It throws in weird, incoherent words, transforming the illusion into a caricature.

I open my eyes and realize that I have to go to the bathroom. What an involved way to let a person know that he has to urinate! Afterward, I return to my bed and lie quietly, amazed at the deviousness of the sleeping brain. Can there be an explanation for all this? Is there some law governing nightmares? One thing is certain: this dream returns like a leitmotif in a symphony of madness.

After a while, I remind myself of my hero, Morris Krakower. What’s happened to him? Oh, yes, his silent opponent is pulling harder, and Morris must let go. So engrossed is he in the tug-of-war that his fear is momentarily forgotten. Suddenly, the other being stops pulling the blanket, and Morris Krakower perceives a shape. He realizes that all this blanket pulling was just a way of drawing his attention to this apparition.

Not far from him, at the foot of the bed, stands Comrade Damschak, who a few years ago travelled to Soviet Russia, published several angry attacks there, in which he accused a number of writers of Trotskyism, and then vanished. The face is Damschak’s, but the body is as if dissected, like the cadavers used in medical school to teach anatomy. The muscles and the blood vessels are laid bare. They glow with their own phosphorescent light. Morris Krakower is so stunned that he again forgets to be afraid. The apparition slowly fades before his astonished gaze. For a few minutes, only a membrane or a faint tracery like a network persists, no longer there but not completely gone. Soon even this tracery dissolves.

Morris Krakower lies motionless for minutes or perhaps seconds (who can measure time under such circumstances?). Then he reaches for the lamp and turns it on. Now he is past fear. He picks up the blanket, which has almost completely fallen off the bed. He knows with an inner certainty that he will now be left alone. This was Comrade Damschak’s way of forcing him to look at his phantom.

But how? And why? How can this be understood? It defies scientific explanation. Like food stuck in the throat, which can’t be swallowed or coughed up, it fixes a question in Morris’s mind that can be neither answered nor dismissed. His brain falls still. For the first time in his memory, he is entirely without thoughts, as if his mind were suspended in a vacuum. He is cold, but he doesn’t cover himself. He has one hope—that the whole thing was a dream. But something tells him that he knows the difference between dreaming and reality. He glances at the clock on the night table—it is a quarter past three. He holds the clock to his ear and listens to its inner mechanism at work. Outside, a trolley car passes by, and he can hear the scraping of the wheels. Reality still exists.

For a long time, Morris sits in his bed without an idea, without a theory—a Leninist who has just seen a ghost. Then he stretches out, covers himself, and lays his head on the pillow. He doesn’t dare turn out the light, but he closes his eyes.

“Well, what does one do now?” he asks himself, and he can find no answer. He falls asleep, and when he wakes up again he knows the answer: it was all a dream. If that were not the case, he, Morris Krakower, would have to surrender everything: Communism, atheism, materialism, the Party, all his convictions and commitments. And what would he do then? Turn religious? Pray in the synagogue? There are facts that a man must disown, even to himself. There are secrets one must take to the grave.

One thing is clear: the real Damschak was not here, because his body is in Russia. What Morris saw was a mental image, which his brain had for some reason constructed. Perhaps it was because Morris and Damschak were close friends, and he hasn’t yet made peace with the fact that Damschak turned traitor in Russia. It is possible for a man to dream while awake.

Morris Krakower falls asleep again. In the morning, when he raises the blinds, the sun bathes the room in light. The winter day is as bright as summer. Morris examines the blanket. He finds the marks that his fingers have left in the weave. The threads look as if they had been teased apart in places. So what does this prove? Undoubtedly, he really pulled the blanket. But the other end of the blanket reveals no sign of a struggle. The ghost has left no trace.

The short speech that is delivered by Comrade Krakower that evening lacks the logic, certainty, and smoothness of the one he gave the previous day. He stammers occasionally; he makes errors. He keeps removing the pince-nez from his nose and replacing them. The essence of his speech is that at the present time there is only one revolutionary party: the Communist Party. The main organ of the Party is the Central Committee, its secretariat. To doubt the Party is to doubt Marx, Lenin, Stalin, the ultimate triumph of the proletariat—in other words, to go over to the camp of capitalism, imperialism, fascism, religion, superstition. ♦
"""
