module Server where

import Signal as S
import Http

serverUrl = "http://10.0.1.73:8000/"

fileName : Signal String
fileName = S.constant "jaures.txt"

textContent : Signal String
textContent = let req = S.map (\x -> Http.get (serverUrl ++ "texts/"  ++ x)) fileName
                  response = Http.send <| req
                  getContent : Http.Response String -> String
                  getContent response = case response of
                      Http.Success str -> str
                      Http.Waiting     -> default_text
                      Http.Failure _ _ -> default_text
              in S.map getContent response

default_text_2 ="""
The βουστροφηδόν Manifesto

January 30th, 2015

Dear reader, how do you your eyes feel? Are they fatigued from the hellish gymnastics required during reading? Have they skipped from the right margin, across the entire block of text, to the left one line too many? Are your eyes desperately searching for the next appropriate line without the slightest visual cue? Let boustrophedon put you at ease--there are no gynastics here, just a comfortable winding stroll through the lines of great literature. Double tap the right side of the screen to advance a page, or double tap the left side of the screen to go back a page.

Boustro etymology. comes from the greek works bous and strophe.

Reading this strange mirrored text is difficult you say? Well, sure, at first... but I'm sure Tony Hawk had difficulty riding switch for the first time, too. Later on, being able to skate with either foot forward became essential for transition skating... Everyone reading today is like a skateboarder who never learned to push with their other foot--we've been cheated of fun and comfort. We are the sorriest oxen in the world, forced to needlessly do twice as much work as necessary.

Step onto the half-pipe of life. Flip turn on your next lap.

Tolstoy reads fine in boustro: Господин этот во все время путешествия старательно избегал общения и знакомства с пассажирами. На заговариванья соседей он отвечал коротко и резко и или читал, или, глядя в окно, курил, или, достав провизию из своего старого мешка, пил чай, или закусывал.

Plato, too, is a delight to read when we take it easy on our eyes: Σωκράτης κατέβην χθὲς εἰς Πειραιᾶ μετὰ Γλαύκωνος τοῦ Ἀρίστωνος προσευξόμενός τε τῇ θεῷ καὶ ἅμα τὴν ἑορτὴν βουλόμενος θεάσασθαι τίνα τρόπον ποιήσουσιν ἅτε νῦν πρῶτον ἄγοντες. καλὴ μὲν οὖν μοι καὶ ἡ τῶν ἐπιχωρίων πομπὴ ἔδοξεν εἶναι, οὐ μέντοι ἧττον ἐφαίνετο πρέπειν ἣν οἱ Θρᾷκες ἔπεμπον.

So we march on, oxen against the plow, bourne ceaselessly along the eterenal es.
"""

default_text ="""
Jean Jaurès

Essay by Leon D. Trotsky

July 1915

A YEAR has passed since the death of the greatest man of the Third Republic. Events the like of which history has not previously known have welled up almost as if to wash away Jaurès’ blood with new blood and to divert attention away from him and to swallow up even his memory. But even the very greatest events have only partially succeeded in this. In France’s political life a great void has been left behind. New leaders of the proletariat answering the revolutionary character of the new era have not yet arisen. The old leaders only make us remember the more clearly that there is now no Jaurès.

The war has thrown on one side not only individual figures but a whole era with them: the era during which the present leading generation in all spheres of life had been educated and brought up. Today this departed era on the one hand attracts our thoughts by the obstinacy of its cultural heritage, the uninterrupted growth of its technology, science and workers’ organizations; and on the other seems petty and characterless in the conservatism of its political life and in the reformist methods of its class struggle.

After the Franco-Prussian War and the Paris Commune (1870-1871) a period of armed peace and political reaction set in. Europe, if one excluded Russia, knew neither war nor revolution. Capital developed on a mighty scale outgrowing the framework of nation-states and overflowing into the remaining countries and subjugating colonies. The working class built its trade unions and its socialist parties. However the whole of the proletarian struggle of this period was impregnated with the spirit of reformism, of adaptation to the existing order and to the nation’s industry and the nation’s state power. After the experience of the Paris Commune the European proletariat did not once pose the question of the conquest of political power in a practical, that is, a revolutionary way. This peaceful, “organic” character of the era reared a whole generation of proletarian leaders thoroughly steeped in distrust for the direct revolutionary mass struggle.

When the war broke out and the nation-state embarked on its campaign with all its forces armed to the teeth, this generation could without difficulty place the majority of the “socialist” leaders down on their knees. The epoch of the Second International has thus ended with the violent wrecking of the official socialist parties. True they are still standing as monuments to a past age and supported both indirectly and forcibly by the governments. But the spirit of proletarian socialism has fled them and they are doomed to collapse. The working masses who have in the past accepted the ideas of socialism are only now, amid the terrible experience of the war, receiving their revolutionary baptism of fire. We are entering upon a period of unprecedented revolutionary earthquakes. New organizations will be brought to the fore by the masses and new leaders will stand at their head.

The two most outstanding representatives of the Second International have left the scene before the onset of the era of storms and earthquakes: namely Bebel and Jaurès. Bebel died in ripe old age having said everything that he was able to say. Jaurès was killed at the age of 55 in the full flower of his creative energy. A pacifist and a sharp opponent of the policies of Russian diplomacy, Jaurès fought right till the last minute against French intervention in the war. It was considered in certain circles that the war of “liberation” could not commence its march other than by stepping over Jaurès’ dead body. And in June 1914 one Villain, some miserable little reactionary, killed Jaurès at a café table. Who guided Villain? Only the French imperialists? Would it not be possible after a diligent investigation to discover behind Villain’s back the hand also of Tsarist diplomacy? This question has frequently been put in socialist circles. When the European revolution turns to the liquidation of the war it will in the course of this uncover the mystery of Jaurès’ death ...

Jaurès was born on September 3, 1859 at Castres in the southern province of Languedoc from where so many great men of France have come: Guizot, Auguste Comte, Lafayette, La Pérouse, Rivarol and others. According to Rappoport’s biography of Jaurès a mixture of races had left a fortunate imprint on the geniuses of this locality which as early as the Middle Ages was the cradle of heresy and free-thinking.

Jaurès’ parents’ family belonged to the middle bourgeoisie and waged a constant struggle for existence. Jaurès even required a sponsor in order that he could complete his studies at the university. In 1881 he finished his course at a teachers’ training college. From 1881 to 1883 he was a teacher at the girls’ grammar school at Albi. He then moved to Toulouse University and was a lecturer there until 1885 when he was first elected to parliament. He was then no more than 26 years of age. From that day until his death Jaurès dissolved into the political struggle and merged with the life of the Third Republic.

Jaurès made his debut in parliament over the question of popular education. La Justice, then the newspaper of the radical, Clemenceau, called Jaurès’ first speech “fine” and wished that the chamber might often hear “a style, so eloquent and full of content”. More than once subsequently Jaurès was to pounce down with the full force of his speech on Clemenceau, the tiger.

In the first period of his activity Jaurès had only a theoretical and at that incomplete acquaintance with socialism. But each new speech brought him closer to the workers’ party. The lack of ideals and the corruptness of the bourgeoisie repelled him irreconcilably.

In 1893 Jaurès finally joined the socialist movement and almost immediately took up one of the leading places in European socialism. At the same time he became the most prominent figure in France’s political life.

In 1894 Jaurès stepped forward in defence of his friend Gèrault Richard, an unattractive figure who had been brought to court for insulting the then president of the republic in the article Down with Casimir. In his speech to the court which was devoted entirely to political ends Jaurès wielded against Casimir-Perrier that terrible power of a spirit in action whose name is hate. In words imbued with mercilessness he characterized the president himself and his immediate forefathers: the usurers who would betray the bourgeoisie to the nobility, the nobility to the bourgeoisie, one dynasty to another, the monarchy to the republic, everyone together to each one as an individual never betraying only themselves. The presiding judge at the court found it necessary to exclaim: “Mr Jaurès, you are digressing too far ... you are comparing Perrier’s house to a brothel.” Jaurès: “I’m not comparing it, I think it’s worse than one.” Gèrault Richard was acquitted. A few days later Casimir-Perrier resigned. Jaurès at once grew by a whole head in public opinion: everyone sensed the menacing force of this tribune.

In the Dreyfus Case Jaurès revealed his full stature. At first as generally in all the critical occasions of his public life, he passed through a period of doubt and weakness when he could be influenced both from the right and from the left. Under the influence of Guesde and Vaillant who treated the Dreyfus Case as a clash between capitalist cliques irrelevant to the proletariat, Jaurès hesitated to get involved in the “case”. The firm example of Zola knocked him off his state of unstable equilibrium, infected him and carried him along. Once swung into motion Jaurès now went through to the end. He was fond of saying about himself: “Ago quod ago” (I do what I do).

In the Dreyfus Case for Jaurès there was summed up and dramatized the fight against clericalism, against reaction, against parliamentary nepotism, against race hate and militarist hysteria, against backstage intrigues amongst the general staff, against the servility of the courts – against all the despicable forces that the powerful party of reaction could swing into motion to achieve its ends.

Jaurès fell upon the anti-Dreyfusite, Mèline who has recently re-emerged as a minister in the “greater” Briand ministry, with the full weight of his anger: “Do you know what we are all suffering from and from just what we shall perish? Let me vouch for this personally: ever since this case opened we have all been dying from half-measures, reticence, equivocation, lies and cowardice. Yes, of equivocation, lies and cowardice.” Reinach tells us: “He was no longer speaking: he roared purple in the face with his arms stretched out towards the ministers who protested and towards the Right who howled.” That was Jaurès!

In 1898 [1] Jaurès managed to proclaim the unity of the Socialist Party. But it proved to be only ephemeral. The participation of the socialist Millerand in the government which resulted from the left bloc policy blew unity apart and during 1900-1901 French socialism once again split in two parties. Jaurès headed one of them – the one which had produced Millerand from its ranks. In the essence of his views Jaurès had been and remained a reformist. But he possessed an astonishing capacity for adaptation: and that included adaptation towards the revolutionary tendencies in the movement. He displayed this subsequently more than once.

Jaurès had entered the party as a mature man with a developed idealist outlook. This did not prevent him placing his powerful neck – Jaurès was distinguished by his athletic build – under the yoke of organizational discipline and more than once he had occasion and need to show that he knew how to obey as well as to give orders. Upon returning from the International Congress at Amsterdam where the policy of dissolving the workers’ party in a left bloc, and participation in governments was condemned, Jaurès openly snapped the thread of the policy of the bloc. The then prime minister, the militant anti-cleric Combes, warned Jaurès that the rupture of the coalition would force him to leave the scene. This did not stop Jaurès. Combes resigned. The unity of the party merged out of the supporters of Jaurès and of Guesde was secured. From that moment onwards Jaurès life merged once and for all with the life of the united party at whose head he stood.

Jaurès’s murder was no accident. It formed the concluding link of a furious campaign of hate, calumny and slander which enemies of every hue waged against him. ‘Whole libraries could be assembled out of the slanders and attacks against Jaurès. Temps, France’s most influential organ every day published an article, and sometimes two the same day, aimed against this political tribune. But they had mainly to attack his ideas and his methods of action: as a personality he remained almost invulnerable, even in France where personal insinuation forms a powerful instrument of political struggle. They could not however get by without smears about German gold ... Jaurès died a poor man. On August 2, 1914 Temps was obliged to acknowledge the ‘absolute honesty’ of its slain foe.

In the summer of 1915 I visited the now famous Café Croissant, two steps from the offices of L’Humanitè, a typical Parisian café: a dirty sawdust-covered floor, leather settees, frayed chairs, marble-topped tables, a low ceiling and with its own special wines and dishes – in short what only Paris has, I was shown a small sofa by the window: on this spot the most brilliant son of modern France was killed by a revolver shot.

His bourgeois family background, school and parliamentary career, his bourgeois marriage, his daughter who was taken by her mother to Holy Communion, editorship of a paper and leadership of a parliamentary party – within this outwardly by no means heroic framework there flowed a life of exceptional tension and of volcanic moral passion.

Jaurès at times called himself the dictator of French socialism and on certain occasions the Right even called him the dictator of the republic. It is beyond doubt that in French socialism he played a role which was second to none. But there was nothing of the tyrant in his “dictatorship”. He ruled without force: a man of great dimensions, with a mighty intellect, the temperament of a genius, an unequalled capacity for work and a voice with the ring of wonder, Jaurès occupied by force of circumstances a first place so far out in front of the second and the third that he could not have experienced the need to reinforce his position by means of backstage manipulation. In this last sphere, Pierre Renaudel, today’s “leader” of social-patriotism had already by then shown himself to be the great master.

Breadth of character repelled Jaurès instinctively from any sort of sectarianism. After wavering one way and the other he would grope his way to that point which seemed to him decisive at the given moment. Between this point of departure and his idealist constructions he would, without any effort of will, win over those points of view which complemented or limited his own, reconcile hostile tendencies and submerge contradictory arguments into a far from impeccable unity. He therefore held sway not only in the National Assembly and on the tribune of parliament, where his unquenchable passion subdued the audience, but also at party congresses where he would dissolve the mutual opposition of the tendencies into diffuse perspectives and flexible formulas. He was in essence an eclectic, but a brilliant one.

“Our duty is lofty and clear: always to propagate the idea, always to awaken and organize energy, always to hope and always to struggle until the final victory.” The whole of Jaurès is expressed in this pattern of forces. His creative energy surges up like a spring in every direction, arousing and organizing energy and thrusting into struggle.

In Rappoport’s accurate expression, Jaurès radiated magnanimity and goodness. Yet at the same time he possessed to the highest degree a talent for concentrated anger: not the sort that blinds and befuddles the brain and brings on political convulsions but rather the sort that harnesses the will and prompts the sharpest descriptions and the most expressive epithets which immediately strike home. We have heard his earlier description of Nrier. You should leaf through his speeches and articles against the black heroes of the Dreyfus Case! This is how Jaurès characterized one of the least significant ones: “G. Brunétier, who in literary history has tried his hand at inane structural systems both shaky and brittle, has at last found refuge beneath the ponderous vaults of the church; now he is attempting to conceal personal bankruptcy of this sort by proclaiming the overall bankruptcy of science and freedom. Having in vain sought to extract from the depths something akin to thought he glorifies authority with his kind of marvellous self-degradation; having in the eyes of the younger generation lost any of that credit which he abused on one occasion with his capacity for empty generalizations he wishes to deaden that free thought which has slipped away from under him.” Woe to him who fell under this heavy hand!

When he entered parliament in 1885 Jaurès took his seat on the benches of the moderate left. But his change to socialism was neither a catastrophe nor a leap. In the initial Jaurèsian “moderation” there were from the start huge funds of positive social humanism which readily developed in a socialist direction. On the other hand his socialism never assumed a sharply delineated class character and never broke from the humanitarian and natural-historical premises which had been deeply implanted in French political thinking by the era of the Revolution.

In 1889 Jaurès addressed the deputies in these words: “Have indeed the geniuses born of the French Revolution been exhausted? Can you not find in the ideas of the revolution the means to provide an answer to all the questions now arising and to all the problems now posed? Has not the revolution preserved its virtue whereby it is capable of giving us an answer to all the changing difficulties through which we have to make our way?” Here the idealism of the democrat remains still quite untouched by a materialist critique. In the days to follow Jaurès was to gain a great deal from Marxism. But he retained a purely democratic motivation in his thinking until the end.

Jaurès emerged on to the political arena at the most dormant stage of the Third Republic which at the time had only 15 years of existence behind it. While backed by no strong traditions it had ranged before it powerful enemies. The fight for the republic, for its existence and for its “purification” formed Jaurès’ basic idea throughout his work. He sought a broader social base for the republic, wanting to bring the republic to the people so that the people through the republic could organize and make the republican state in the final count the instrument of a socialist economy. For Jaurès, the democrat, socialism was the only reliable means of consolidating the republic and its only possible fulfilment. In his mind there was no contradiction between bourgeois politics and socialism, that is, the contradiction which reflects the historical chasm between the proletariat and the democratic bourgeoisie. In his tireless striving towards an idealist synthesis Jaurès emerged in his first period as the democrat ready to father socialism while in the second period of his activity he came forward as a socialist bearing the responsibility for the whole of democracy.

L’Humanitè – it was not by chance that Jaurès so named the newspaper he created. Socialism for him was not the theoretical expression of the class struggle of the proletariat.

On the contrary in his eyes the proletariat remained a historical force at the service of justice, freedom and humanity. Above the proletariat he assigned a higher place to the independent idea of ‘humanity’ which on the lips of the run of the mill French haranguers remains a hollow phrase but which for Jaurès was filled with an unfeigned and positive idealism.

In politics Jaurès united in himself a capacity for extreme idealistic abstraction with a powerful intuitive sensitivity to reality. This combination ran through the whole of his activity.

The ethereal ideas of Justice and Good with him went hand in hand with an empirical appraisal of even the secondary realities of life. For all his moral optimism Jaurès had a fine understanding of circumstances and people and knew well how to turn both the one and the other to advantage. He had a great deal of common sense. He was often called a sly peasant. But thanks to his single scale of values his common sense was alien to vulgarity. And the most important thing was that this common sense stood at the service of the idea.

Jaurès was an ideologist, a herald of ideas in the sense in which the now half-forgotten Alfred Fouille spoke of the motive ideas of history. Napoleon spoke of the “ideologists” (the very word belongs to him) with the contempt of the artillerist. Yet Napoleon himself was the ideologist of the new militarism. The ideologist does not simply adjust himself to reality but from it abstracts the “idea” and this idea leads him to his ultimate conclusions. This gives the ideologist, in an era favourable to him, successes such as the vulgar practice can never achieve; but it is preciseiy this too which prepares dizzying falls for him when the objective conditions turn against him.

The doctrinaire becomes frozen to a theory whose spirit he fortifies. The opportunist “practico” acquires certain tricks of the political trade but then after a turning point in the situation feels himself to be like a hand weaver made redundant by the mechanical loom. The full-blooded ideologist is powerless only at that moment when history disarms him ideologically but he is capable of rapidly rearming himself and by assimilating the ideas of the new era can come out on top.

Jaurès was an ideologist. From the political situation he would abstract its idea and in pursuance of that idea he would not stop halfway. Thus in the period of the Dreyfus Case he carried the idea of collaboration with the bourgeois left to its ultimate conclusion and passionately supported Millerand, a vulgar political empiricist in whom there was and is nothing of ideology nor of its courage and its sweep. By following this path Jaurès ended up in a political blind alley; with the ingenuous and unstinted blindness of the ideologist who is ready to close his eyes to the facts so as not to deny the motive-ideas.

Jaurès fought against the danger of a European war with a genuine ideological passion. In this struggle, as in every one he waged, he utilized two methods which conflicted deeply with the class character of his party and which to many of his comrades seemed risky to say the least. He would take a great deal upon himself and upon his personal strength, resourcefulness and improvization and in the corridors of parliament he would with exaggerated hopes waylay ministers and diplomats and pin them to the wall with the weight of his reasoning. But corridor discussions and effects did not in themselves flow from Jaurès’ nature and were not in the least elevated into a system: he was a political ideologist and not a doctrinaire of opportunism. In the service of the idea which possessed him he was capable of using with an equal passion both the most opportunist and the most revolutionary means and if this idea answered the character of the epoch he was capable of achieving results like no one else could. But he was moving towards catastrophic defeats. In politics he like Napoleon had known bath his Austerlitz and his Waterloo. The world war would have placed Jaurès face to face with those questions which have split European socialism into two irreconcilable camps. Which position would he have taken? Without doubt the patriotic. But he would have never passively reconciled himself to the degradation of the French Socialist Party which was to befall it under the leadership of Guesde, Renaudel, Sembat and Thomas. And we have every right to suppose that in the revolution to come the great tribune would unequivocally define his place and develop his forces to the limit.

A senseless piece of lead released Jaurès from his supreme political test.

Jaurès was the embodiment of the force of an individual. His spiritual profile corresponded fully to his physical build: elegance and grace as qualities in themselves were foreign to him; yet inborn in his speeches and actions was that higher beauty which distinguishes the manifestations of a self-confident creative force. If one considers a transparent clarity and refinement of form to be the all-embracing features of the French spirit then Jaurès may appear to be little typical of France. But in actual fact he was a Frenchman to the highest degree. Alongside Voltaire, Boileau, and also Anatole France in literature, and alongside the heroes of the old Gironde or today’s Viviani and Deschanel in politics, France knew too Rabelais, Balzac and Zola in literature and Mirabeau, Danton and Taures in politics. These are a race of men with powerful and intellectual sinews, a positive intrepidity, a great force of passion and a concentrated will. These are an athletic type. It was enough to hear the Zeus-like voice of Jaurès and to see his muscular face lit up by inner rays, his imperious nose, and his stubborn, unbending neck to say to oneself: ‘Ecce homo!’ (Behold the man!).

Jaurès’ principal strength as an orator was the same as what made him strong as a politician: a tense, outwardly-trained passion and the will to action. In Jaurès’ oratorical creations there is nothing self-contained – he was not an orator but something more: for him the art of the word was not an end but the means to an end. Hence, while being a very powerful orator – perhaps the most powerful of all those humanity has produced – he stood above the oratorial art: he was always higher than his speech as a craftsman is higher than his tool.

Zola was an artist: he started from the naturalist school of moral impassivity and then suddenly erupted with the thunder-clap of his letter J’accuse (I accuse). There was implanted in him a mighty moral force which found its expession in his titanic creative output but which was in essence broader than artistry: this was a human force of destruction and of creation. So it was with Jaurès too. In his oratorical skill and his politics despite all their inevitable limitations, a regal personality with a real and genuine moral fibre revealed itself with a stubborn will to struggle and to victory. He mounted the tribune not in order to relieve himself of some images nor in order to provide the most complete expression to a series of thoughts but in order to weld together disparate wills into a unity of aim; in his speech there is none of the Latin rhetorical art for art’s sake – it was always purposeful and utilitarian; and precisely because of this it represents a higher form of human creation. With equal freedom Jaurès could make use now of the reasoned argument, now of the artistic image and now of the appeal to human emotions. He would simultaneously play on thougbt, aesthetic sensitivity and the will. But all these forces of his oratorical political and human genius were subordinated to his main force – the will to action.

I have heard Jaurès at sessions of the National Assembly in Paris, at international congresses and in congress commissions. And each time I would listen to him as if for the first time. He did not accumulate set clichès, he never basically repeated himself, each time he rediscovered himself and each time he mobilized anew the many-sided forces of his spirit. For all the power of his force, which was elemental like a waterfall, there was in him a great deal of gentleness which shone like a gleam of a higher culture of the spirit. He would blast crags, roar and shake his audience but he never deafened himself, always kept his guard and astutely captured every comment, snatched it up, parrying the criticism at times without mercy like a hurricane sweeping all resistance from its path and at times magnanimously and tenderly like a tutor or an elder brother. In this way a ten-ton steam-roller can pulverize a stone slab and beat out gold leaf to a tenth of a millimetre.

Paul Lafargue, a Marxist and an ideological opponent of Jaurès, called him a human devil. This devilish power – as a matter of fact it was a genuinely divine power – everyone, both his friends and his enemies, sensed in him. And his enemies frequently as if bewitched became expectant and spellbound when confronted by the torrent of his speech which was a will clothed in words;, exactly as if they were faced with a phenomenon of nature.

Three years ago this figure, one of nature’s rare gifts to mankind, perished without exhausting himself. Perhaps for an aesthetically rounded image Jaurès needed such a death. Great men know how to die in their own way. Tolstoy sensing death on the way took up his crook and went off into exile from the society which he rejected and died on a remote station like a pilgrim. Lafargue in whom the Epicurean matched the Stoic lived on until the age of seventy in an atmosphere of repose and thought and then he said to himself “enough” and injected poison into his vein. Jaurès as the athlete of the idea died in the ring while fighting against the greatest disaster which has ever befallen mankind and humanity – l’humanitè – while fighting against the war. And he will remain in the memory of mankind as a foreteller and a precursor of that more elevated human type which shall be born of the sufferings and defeats and out of hopes and struggle.

Kievskaya Mysl, No.196, July 17, 1915
"""
